version: '2'
run:
  allow-parallel-runners: true
linters:
  default: standard
  enable:
    - containedctx
    - contextcheck
    - dupword
    - embeddedstructfieldcheck
    - exhaustive
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funcorder
    - goconst
    - gocritic
    - godot
    - godox
    - gosec
    - misspell
    - intrange
    - musttag
    - makezero
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    # - paralleltest
    - prealloc
    - protogetter
    - predeclared
    - recvcheck
    - thelper
    # - tparallel
    - unconvert
    - unparam
    - whitespace
    # - wrapcheck
  settings:
    goconst:
      min-occurrences: 2
      numbers: true
    gocritic:
      enabled-checks:
        - badLock
        - filepathJoin
        - sortSlice
        - sprintfQuotedString
        - syncMapLoadAndDelete
        - weakCond
        - boolExprSimplify
        - httpNoBody
        - nestingReduce
        - preferFilepathJoin
        - redundantSprint
        - stringConcatSimplify
        - timeExprSimplify
        - typeAssertChain
        - yodaStyleExpr
        - truncateCmp
        - equalFold
        - preferDecodeRune
        - preferFprint
        - preferStringWriter
        - preferWriteByte
        - sliceClear
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
  exclusions:
    paths:
      - .*\.pb\.go
      - .*\.pulsar\.go
      - api/
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/cosmos/,cosmossdk.io/,github.com/cometbft/)
        - blank
        - dot
        - localmodule
      custom-order: true
      no-inline-comments: true
      no-prefix-comments: true
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
    golines:
      shorten-comments: true
