// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package entrypointv1

import (
	_ "cosmossdk.io/api/amino"
	_ "cosmossdk.io/api/cosmos/msg/v1"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "github.com/noble-assets/orbiter/v2/api/core/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_MsgReceiveCCTPMessage                      protoreflect.MessageDescriptor
	fd_MsgReceiveCCTPMessage_signer               protoreflect.FieldDescriptor
	fd_MsgReceiveCCTPMessage_transfer_message     protoreflect.FieldDescriptor
	fd_MsgReceiveCCTPMessage_transfer_attestation protoreflect.FieldDescriptor
	fd_MsgReceiveCCTPMessage_payload_message      protoreflect.FieldDescriptor
	fd_MsgReceiveCCTPMessage_payload_attestation  protoreflect.FieldDescriptor
)

func init() {
	file_noble_orbiter_entrypoint_v1_cctp_proto_init()
	md_MsgReceiveCCTPMessage = File_noble_orbiter_entrypoint_v1_cctp_proto.Messages().ByName("MsgReceiveCCTPMessage")
	fd_MsgReceiveCCTPMessage_signer = md_MsgReceiveCCTPMessage.Fields().ByName("signer")
	fd_MsgReceiveCCTPMessage_transfer_message = md_MsgReceiveCCTPMessage.Fields().ByName("transfer_message")
	fd_MsgReceiveCCTPMessage_transfer_attestation = md_MsgReceiveCCTPMessage.Fields().ByName("transfer_attestation")
	fd_MsgReceiveCCTPMessage_payload_message = md_MsgReceiveCCTPMessage.Fields().ByName("payload_message")
	fd_MsgReceiveCCTPMessage_payload_attestation = md_MsgReceiveCCTPMessage.Fields().ByName("payload_attestation")
}

var _ protoreflect.Message = (*fastReflection_MsgReceiveCCTPMessage)(nil)

type fastReflection_MsgReceiveCCTPMessage MsgReceiveCCTPMessage

func (x *MsgReceiveCCTPMessage) ProtoReflect() protoreflect.Message {
	return (*fastReflection_MsgReceiveCCTPMessage)(x)
}

func (x *MsgReceiveCCTPMessage) slowProtoReflect() protoreflect.Message {
	mi := &file_noble_orbiter_entrypoint_v1_cctp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_MsgReceiveCCTPMessage_messageType fastReflection_MsgReceiveCCTPMessage_messageType
var _ protoreflect.MessageType = fastReflection_MsgReceiveCCTPMessage_messageType{}

type fastReflection_MsgReceiveCCTPMessage_messageType struct{}

func (x fastReflection_MsgReceiveCCTPMessage_messageType) Zero() protoreflect.Message {
	return (*fastReflection_MsgReceiveCCTPMessage)(nil)
}
func (x fastReflection_MsgReceiveCCTPMessage_messageType) New() protoreflect.Message {
	return new(fastReflection_MsgReceiveCCTPMessage)
}
func (x fastReflection_MsgReceiveCCTPMessage_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_MsgReceiveCCTPMessage
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_MsgReceiveCCTPMessage) Descriptor() protoreflect.MessageDescriptor {
	return md_MsgReceiveCCTPMessage
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_MsgReceiveCCTPMessage) Type() protoreflect.MessageType {
	return _fastReflection_MsgReceiveCCTPMessage_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_MsgReceiveCCTPMessage) New() protoreflect.Message {
	return new(fastReflection_MsgReceiveCCTPMessage)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_MsgReceiveCCTPMessage) Interface() protoreflect.ProtoMessage {
	return (*MsgReceiveCCTPMessage)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_MsgReceiveCCTPMessage) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Signer != "" {
		value := protoreflect.ValueOfString(x.Signer)
		if !f(fd_MsgReceiveCCTPMessage_signer, value) {
			return
		}
	}
	if len(x.TransferMessage) != 0 {
		value := protoreflect.ValueOfBytes(x.TransferMessage)
		if !f(fd_MsgReceiveCCTPMessage_transfer_message, value) {
			return
		}
	}
	if len(x.TransferAttestation) != 0 {
		value := protoreflect.ValueOfBytes(x.TransferAttestation)
		if !f(fd_MsgReceiveCCTPMessage_transfer_attestation, value) {
			return
		}
	}
	if len(x.PayloadMessage) != 0 {
		value := protoreflect.ValueOfBytes(x.PayloadMessage)
		if !f(fd_MsgReceiveCCTPMessage_payload_message, value) {
			return
		}
	}
	if len(x.PayloadAttestation) != 0 {
		value := protoreflect.ValueOfBytes(x.PayloadAttestation)
		if !f(fd_MsgReceiveCCTPMessage_payload_attestation, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_MsgReceiveCCTPMessage) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.signer":
		return x.Signer != ""
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.transfer_message":
		return len(x.TransferMessage) != 0
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.transfer_attestation":
		return len(x.TransferAttestation) != 0
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.payload_message":
		return len(x.PayloadMessage) != 0
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.payload_attestation":
		return len(x.PayloadAttestation) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage"))
		}
		panic(fmt.Errorf("message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgReceiveCCTPMessage) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.signer":
		x.Signer = ""
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.transfer_message":
		x.TransferMessage = nil
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.transfer_attestation":
		x.TransferAttestation = nil
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.payload_message":
		x.PayloadMessage = nil
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.payload_attestation":
		x.PayloadAttestation = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage"))
		}
		panic(fmt.Errorf("message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_MsgReceiveCCTPMessage) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.signer":
		value := x.Signer
		return protoreflect.ValueOfString(value)
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.transfer_message":
		value := x.TransferMessage
		return protoreflect.ValueOfBytes(value)
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.transfer_attestation":
		value := x.TransferAttestation
		return protoreflect.ValueOfBytes(value)
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.payload_message":
		value := x.PayloadMessage
		return protoreflect.ValueOfBytes(value)
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.payload_attestation":
		value := x.PayloadAttestation
		return protoreflect.ValueOfBytes(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage"))
		}
		panic(fmt.Errorf("message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgReceiveCCTPMessage) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.signer":
		x.Signer = value.Interface().(string)
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.transfer_message":
		x.TransferMessage = value.Bytes()
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.transfer_attestation":
		x.TransferAttestation = value.Bytes()
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.payload_message":
		x.PayloadMessage = value.Bytes()
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.payload_attestation":
		x.PayloadAttestation = value.Bytes()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage"))
		}
		panic(fmt.Errorf("message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgReceiveCCTPMessage) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.signer":
		panic(fmt.Errorf("field signer of message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage is not mutable"))
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.transfer_message":
		panic(fmt.Errorf("field transfer_message of message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage is not mutable"))
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.transfer_attestation":
		panic(fmt.Errorf("field transfer_attestation of message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage is not mutable"))
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.payload_message":
		panic(fmt.Errorf("field payload_message of message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage is not mutable"))
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.payload_attestation":
		panic(fmt.Errorf("field payload_attestation of message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage"))
		}
		panic(fmt.Errorf("message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_MsgReceiveCCTPMessage) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.signer":
		return protoreflect.ValueOfString("")
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.transfer_message":
		return protoreflect.ValueOfBytes(nil)
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.transfer_attestation":
		return protoreflect.ValueOfBytes(nil)
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.payload_message":
		return protoreflect.ValueOfBytes(nil)
	case "noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage.payload_attestation":
		return protoreflect.ValueOfBytes(nil)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage"))
		}
		panic(fmt.Errorf("message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_MsgReceiveCCTPMessage) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_MsgReceiveCCTPMessage) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgReceiveCCTPMessage) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_MsgReceiveCCTPMessage) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_MsgReceiveCCTPMessage) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*MsgReceiveCCTPMessage)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Signer)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.TransferMessage)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.TransferAttestation)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.PayloadMessage)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.PayloadAttestation)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*MsgReceiveCCTPMessage)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.PayloadAttestation) > 0 {
			i -= len(x.PayloadAttestation)
			copy(dAtA[i:], x.PayloadAttestation)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PayloadAttestation)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.PayloadMessage) > 0 {
			i -= len(x.PayloadMessage)
			copy(dAtA[i:], x.PayloadMessage)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PayloadMessage)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.TransferAttestation) > 0 {
			i -= len(x.TransferAttestation)
			copy(dAtA[i:], x.TransferAttestation)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TransferAttestation)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.TransferMessage) > 0 {
			i -= len(x.TransferMessage)
			copy(dAtA[i:], x.TransferMessage)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TransferMessage)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Signer) > 0 {
			i -= len(x.Signer)
			copy(dAtA[i:], x.Signer)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Signer)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*MsgReceiveCCTPMessage)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: MsgReceiveCCTPMessage: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: MsgReceiveCCTPMessage: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Signer = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TransferMessage", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TransferMessage = append(x.TransferMessage[:0], dAtA[iNdEx:postIndex]...)
				if x.TransferMessage == nil {
					x.TransferMessage = []byte{}
				}
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TransferAttestation", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TransferAttestation = append(x.TransferAttestation[:0], dAtA[iNdEx:postIndex]...)
				if x.TransferAttestation == nil {
					x.TransferAttestation = []byte{}
				}
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PayloadMessage", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PayloadMessage = append(x.PayloadMessage[:0], dAtA[iNdEx:postIndex]...)
				if x.PayloadMessage == nil {
					x.PayloadMessage = []byte{}
				}
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PayloadAttestation", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PayloadAttestation = append(x.PayloadAttestation[:0], dAtA[iNdEx:postIndex]...)
				if x.PayloadAttestation == nil {
					x.PayloadAttestation = []byte{}
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_MsgReceiveCCTPMessageResponse protoreflect.MessageDescriptor
)

func init() {
	file_noble_orbiter_entrypoint_v1_cctp_proto_init()
	md_MsgReceiveCCTPMessageResponse = File_noble_orbiter_entrypoint_v1_cctp_proto.Messages().ByName("MsgReceiveCCTPMessageResponse")
}

var _ protoreflect.Message = (*fastReflection_MsgReceiveCCTPMessageResponse)(nil)

type fastReflection_MsgReceiveCCTPMessageResponse MsgReceiveCCTPMessageResponse

func (x *MsgReceiveCCTPMessageResponse) ProtoReflect() protoreflect.Message {
	return (*fastReflection_MsgReceiveCCTPMessageResponse)(x)
}

func (x *MsgReceiveCCTPMessageResponse) slowProtoReflect() protoreflect.Message {
	mi := &file_noble_orbiter_entrypoint_v1_cctp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_MsgReceiveCCTPMessageResponse_messageType fastReflection_MsgReceiveCCTPMessageResponse_messageType
var _ protoreflect.MessageType = fastReflection_MsgReceiveCCTPMessageResponse_messageType{}

type fastReflection_MsgReceiveCCTPMessageResponse_messageType struct{}

func (x fastReflection_MsgReceiveCCTPMessageResponse_messageType) Zero() protoreflect.Message {
	return (*fastReflection_MsgReceiveCCTPMessageResponse)(nil)
}
func (x fastReflection_MsgReceiveCCTPMessageResponse_messageType) New() protoreflect.Message {
	return new(fastReflection_MsgReceiveCCTPMessageResponse)
}
func (x fastReflection_MsgReceiveCCTPMessageResponse_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_MsgReceiveCCTPMessageResponse
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) Descriptor() protoreflect.MessageDescriptor {
	return md_MsgReceiveCCTPMessageResponse
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) Type() protoreflect.MessageType {
	return _fastReflection_MsgReceiveCCTPMessageResponse_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) New() protoreflect.Message {
	return new(fastReflection_MsgReceiveCCTPMessageResponse)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) Interface() protoreflect.ProtoMessage {
	return (*MsgReceiveCCTPMessageResponse)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessageResponse"))
		}
		panic(fmt.Errorf("message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessageResponse does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessageResponse"))
		}
		panic(fmt.Errorf("message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessageResponse does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessageResponse"))
		}
		panic(fmt.Errorf("message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessageResponse does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessageResponse"))
		}
		panic(fmt.Errorf("message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessageResponse does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessageResponse"))
		}
		panic(fmt.Errorf("message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessageResponse does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessageResponse"))
		}
		panic(fmt.Errorf("message noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessageResponse does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessageResponse", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_MsgReceiveCCTPMessageResponse) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*MsgReceiveCCTPMessageResponse)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*MsgReceiveCCTPMessageResponse)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*MsgReceiveCCTPMessageResponse)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: MsgReceiveCCTPMessageResponse: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: MsgReceiveCCTPMessageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: noble/orbiter/entrypoint/v1/cctp.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgCCTPEntrypoint ... TODO
type MsgReceiveCCTPMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signer              string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	TransferMessage     []byte `protobuf:"bytes,2,opt,name=transfer_message,json=transferMessage,proto3" json:"transfer_message,omitempty"`
	TransferAttestation []byte `protobuf:"bytes,3,opt,name=transfer_attestation,json=transferAttestation,proto3" json:"transfer_attestation,omitempty"`
	PayloadMessage      []byte `protobuf:"bytes,4,opt,name=payload_message,json=payloadMessage,proto3" json:"payload_message,omitempty"`
	PayloadAttestation  []byte `protobuf:"bytes,5,opt,name=payload_attestation,json=payloadAttestation,proto3" json:"payload_attestation,omitempty"`
}

func (x *MsgReceiveCCTPMessage) Reset() {
	*x = MsgReceiveCCTPMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noble_orbiter_entrypoint_v1_cctp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgReceiveCCTPMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgReceiveCCTPMessage) ProtoMessage() {}

// Deprecated: Use MsgReceiveCCTPMessage.ProtoReflect.Descriptor instead.
func (*MsgReceiveCCTPMessage) Descriptor() ([]byte, []int) {
	return file_noble_orbiter_entrypoint_v1_cctp_proto_rawDescGZIP(), []int{0}
}

func (x *MsgReceiveCCTPMessage) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

func (x *MsgReceiveCCTPMessage) GetTransferMessage() []byte {
	if x != nil {
		return x.TransferMessage
	}
	return nil
}

func (x *MsgReceiveCCTPMessage) GetTransferAttestation() []byte {
	if x != nil {
		return x.TransferAttestation
	}
	return nil
}

func (x *MsgReceiveCCTPMessage) GetPayloadMessage() []byte {
	if x != nil {
		return x.PayloadMessage
	}
	return nil
}

func (x *MsgReceiveCCTPMessage) GetPayloadAttestation() []byte {
	if x != nil {
		return x.PayloadAttestation
	}
	return nil
}

// MsgReceiveCCTPMessageResponse is the response to the MsgReceiveCCTPMessage.
type MsgReceiveCCTPMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgReceiveCCTPMessageResponse) Reset() {
	*x = MsgReceiveCCTPMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noble_orbiter_entrypoint_v1_cctp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgReceiveCCTPMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgReceiveCCTPMessageResponse) ProtoMessage() {}

// Deprecated: Use MsgReceiveCCTPMessageResponse.ProtoReflect.Descriptor instead.
func (*MsgReceiveCCTPMessageResponse) Descriptor() ([]byte, []int) {
	return file_noble_orbiter_entrypoint_v1_cctp_proto_rawDescGZIP(), []int{1}
}

var File_noble_orbiter_entrypoint_v1_cctp_proto protoreflect.FileDescriptor

var file_noble_orbiter_entrypoint_v1_cctp_proto_rawDesc = []byte{
	0x0a, 0x26, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2f, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x65, 0x72, 0x2f,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x63,
	0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2e,
	0x6f, 0x72, 0x62, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x11, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x6d, 0x69,
	0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x19, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x67, 0x6f,
	0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x23, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2f, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x65,
	0x72, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x02, 0x0a, 0x15, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x43, 0x43, 0x54, 0x50, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x18, 0xd2, 0xb4, 0x2d, 0x14, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x31,
	0x0a, 0x14, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x61, 0x74, 0x74, 0x65, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x13, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x13, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x10, 0x82, 0xe7, 0xb0,
	0x2a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x8a, 0xe7, 0xb0, 0x2a, 0x00, 0x22, 0x1f, 0x0a,
	0x1d, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x43, 0x43, 0x54, 0x50, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x93,
	0x01, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x84, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x43, 0x43, 0x54, 0x50, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x32, 0x2e,
	0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x65, 0x6e,
	0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x43, 0x43, 0x54, 0x50, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x3a, 0x2e, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x65,
	0x72, 0x2e, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x43, 0x43, 0x54, 0x50, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x05, 0x80,
	0xe7, 0xb0, 0x2a, 0x01, 0x42, 0x8c, 0x02, 0x0a, 0x1f, 0x63, 0x6f, 0x6d, 0x2e, 0x6e, 0x6f, 0x62,
	0x6c, 0x65, 0x2e, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x43, 0x63, 0x74, 0x70, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2d, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x6f,
	0x72, 0x62, 0x69, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f,
	0x62, 0x6c, 0x65, 0x2f, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x65, 0x72, 0x2f, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4e, 0x4f, 0x45, 0xaa, 0x02, 0x1b, 0x4e,
	0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x4f, 0x72, 0x62, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x1b, 0x4e, 0x6f, 0x62,
	0x6c, 0x65, 0x5c, 0x4f, 0x72, 0x62, 0x69, 0x74, 0x65, 0x72, 0x5c, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x27, 0x4e, 0x6f, 0x62, 0x6c, 0x65,
	0x5c, 0x4f, 0x72, 0x62, 0x69, 0x74, 0x65, 0x72, 0x5c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x1e, 0x4e, 0x6f, 0x62, 0x6c, 0x65, 0x3a, 0x3a, 0x4f, 0x72, 0x62, 0x69,
	0x74, 0x65, 0x72, 0x3a, 0x3a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x3a,
	0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_noble_orbiter_entrypoint_v1_cctp_proto_rawDescOnce sync.Once
	file_noble_orbiter_entrypoint_v1_cctp_proto_rawDescData = file_noble_orbiter_entrypoint_v1_cctp_proto_rawDesc
)

func file_noble_orbiter_entrypoint_v1_cctp_proto_rawDescGZIP() []byte {
	file_noble_orbiter_entrypoint_v1_cctp_proto_rawDescOnce.Do(func() {
		file_noble_orbiter_entrypoint_v1_cctp_proto_rawDescData = protoimpl.X.CompressGZIP(file_noble_orbiter_entrypoint_v1_cctp_proto_rawDescData)
	})
	return file_noble_orbiter_entrypoint_v1_cctp_proto_rawDescData
}

var file_noble_orbiter_entrypoint_v1_cctp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_noble_orbiter_entrypoint_v1_cctp_proto_goTypes = []interface{}{
	(*MsgReceiveCCTPMessage)(nil),         // 0: noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage
	(*MsgReceiveCCTPMessageResponse)(nil), // 1: noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessageResponse
}
var file_noble_orbiter_entrypoint_v1_cctp_proto_depIdxs = []int32{
	0, // 0: noble.orbiter.entrypoint.v1.Msg.ReceiveCCTPMessage:input_type -> noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessage
	1, // 1: noble.orbiter.entrypoint.v1.Msg.ReceiveCCTPMessage:output_type -> noble.orbiter.entrypoint.v1.MsgReceiveCCTPMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_noble_orbiter_entrypoint_v1_cctp_proto_init() }
func file_noble_orbiter_entrypoint_v1_cctp_proto_init() {
	if File_noble_orbiter_entrypoint_v1_cctp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_noble_orbiter_entrypoint_v1_cctp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgReceiveCCTPMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noble_orbiter_entrypoint_v1_cctp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgReceiveCCTPMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_noble_orbiter_entrypoint_v1_cctp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noble_orbiter_entrypoint_v1_cctp_proto_goTypes,
		DependencyIndexes: file_noble_orbiter_entrypoint_v1_cctp_proto_depIdxs,
		MessageInfos:      file_noble_orbiter_entrypoint_v1_cctp_proto_msgTypes,
	}.Build()
	File_noble_orbiter_entrypoint_v1_cctp_proto = out.File
	file_noble_orbiter_entrypoint_v1_cctp_proto_rawDesc = nil
	file_noble_orbiter_entrypoint_v1_cctp_proto_goTypes = nil
	file_noble_orbiter_entrypoint_v1_cctp_proto_depIdxs = nil
}
