// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: noble/orbiter/component/forwarder/v1/tx.proto

package forwarder

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	core "orbiter.dev/types/core"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgPauseProtocol pauses an entire forwarding protocol.
type MsgPauseProtocol struct {
	// Address of the signer who is requesting to pause the protocol.
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// Bridge protocol to pause.
	ProtocolId core.ProtocolID `protobuf:"varint,2,opt,name=protocol_id,json=protocolId,proto3,enum=noble.orbiter.core.v1.ProtocolID" json:"protocol_id,omitempty"`
}

func (m *MsgPauseProtocol) Reset()         { *m = MsgPauseProtocol{} }
func (m *MsgPauseProtocol) String() string { return proto.CompactTextString(m) }
func (*MsgPauseProtocol) ProtoMessage()    {}
func (*MsgPauseProtocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d12dabcf7836b4c, []int{0}
}
func (m *MsgPauseProtocol) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPauseProtocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPauseProtocol.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPauseProtocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPauseProtocol.Merge(m, src)
}
func (m *MsgPauseProtocol) XXX_Size() int {
	return m.Size()
}
func (m *MsgPauseProtocol) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPauseProtocol.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPauseProtocol proto.InternalMessageInfo

// MsgPauseProtocolResponse is the response type from a MsgPauseProtocol request.
type MsgPauseProtocolResponse struct {
}

func (m *MsgPauseProtocolResponse) Reset()         { *m = MsgPauseProtocolResponse{} }
func (m *MsgPauseProtocolResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPauseProtocolResponse) ProtoMessage()    {}
func (*MsgPauseProtocolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d12dabcf7836b4c, []int{1}
}
func (m *MsgPauseProtocolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPauseProtocolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPauseProtocolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPauseProtocolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPauseProtocolResponse.Merge(m, src)
}
func (m *MsgPauseProtocolResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPauseProtocolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPauseProtocolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPauseProtocolResponse proto.InternalMessageInfo

// MsgPauseCrossChains pauses specific counterparty pairs for a protocol.
type MsgPauseCrossChains struct {
	// Address of the signer who is requesting to pause the counterparty pairs.
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// Bridge protocol to pause.
	ProtocolId core.ProtocolID `protobuf:"varint,2,opt,name=protocol_id,json=protocolId,proto3,enum=noble.orbiter.core.v1.ProtocolID" json:"protocol_id,omitempty"`
	// List of identifiers of destinations that must be paused.
	CounterpartyIds []string `protobuf:"bytes,3,rep,name=counterparty_ids,json=counterpartyIds,proto3" json:"counterparty_ids,omitempty"`
}

func (m *MsgPauseCrossChains) Reset()         { *m = MsgPauseCrossChains{} }
func (m *MsgPauseCrossChains) String() string { return proto.CompactTextString(m) }
func (*MsgPauseCrossChains) ProtoMessage()    {}
func (*MsgPauseCrossChains) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d12dabcf7836b4c, []int{2}
}
func (m *MsgPauseCrossChains) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPauseCrossChains) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPauseCrossChains.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPauseCrossChains) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPauseCrossChains.Merge(m, src)
}
func (m *MsgPauseCrossChains) XXX_Size() int {
	return m.Size()
}
func (m *MsgPauseCrossChains) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPauseCrossChains.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPauseCrossChains proto.InternalMessageInfo

// MsgPauseCrossChainsResponse is the response type
// from a MsgPauseCrossChains request.
type MsgPauseCrossChainsResponse struct {
}

func (m *MsgPauseCrossChainsResponse) Reset()         { *m = MsgPauseCrossChainsResponse{} }
func (m *MsgPauseCrossChainsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPauseCrossChainsResponse) ProtoMessage()    {}
func (*MsgPauseCrossChainsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d12dabcf7836b4c, []int{3}
}
func (m *MsgPauseCrossChainsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPauseCrossChainsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPauseCrossChainsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPauseCrossChainsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPauseCrossChainsResponse.Merge(m, src)
}
func (m *MsgPauseCrossChainsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPauseCrossChainsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPauseCrossChainsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPauseCrossChainsResponse proto.InternalMessageInfo

// MsgUnpauseProtocol resumes an entire forwarding protocol.
type MsgUnpauseProtocol struct {
	// Address of the signer who is requesting to unpause the protocol.
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// Bridge protocol to unpause.
	ProtocolId core.ProtocolID `protobuf:"varint,2,opt,name=protocol_id,json=protocolId,proto3,enum=noble.orbiter.core.v1.ProtocolID" json:"protocol_id,omitempty"`
}

func (m *MsgUnpauseProtocol) Reset()         { *m = MsgUnpauseProtocol{} }
func (m *MsgUnpauseProtocol) String() string { return proto.CompactTextString(m) }
func (*MsgUnpauseProtocol) ProtoMessage()    {}
func (*MsgUnpauseProtocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d12dabcf7836b4c, []int{4}
}
func (m *MsgUnpauseProtocol) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnpauseProtocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnpauseProtocol.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnpauseProtocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnpauseProtocol.Merge(m, src)
}
func (m *MsgUnpauseProtocol) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnpauseProtocol) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnpauseProtocol.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnpauseProtocol proto.InternalMessageInfo

// MsgUnpauseProtocolResponse is the response type from a MsgUnpauseProtocol request.
type MsgUnpauseProtocolResponse struct {
}

func (m *MsgUnpauseProtocolResponse) Reset()         { *m = MsgUnpauseProtocolResponse{} }
func (m *MsgUnpauseProtocolResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUnpauseProtocolResponse) ProtoMessage()    {}
func (*MsgUnpauseProtocolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d12dabcf7836b4c, []int{5}
}
func (m *MsgUnpauseProtocolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnpauseProtocolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnpauseProtocolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnpauseProtocolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnpauseProtocolResponse.Merge(m, src)
}
func (m *MsgUnpauseProtocolResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnpauseProtocolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnpauseProtocolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnpauseProtocolResponse proto.InternalMessageInfo

// MsgUnpauseCrossChains resumes specific counterparty pairs for a protocol.
type MsgUnpauseCrossChains struct {
	// Address of the signer who is requesting to unpause the counterparty pairs.
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// Bridge protocol to unpause.
	ProtocolId core.ProtocolID `protobuf:"varint,2,opt,name=protocol_id,json=protocolId,proto3,enum=noble.orbiter.core.v1.ProtocolID" json:"protocol_id,omitempty"`
	// List of identifiers of destinations that must be unpaused.
	CounterpartyIds []string `protobuf:"bytes,3,rep,name=counterparty_ids,json=counterpartyIds,proto3" json:"counterparty_ids,omitempty"`
}

func (m *MsgUnpauseCrossChains) Reset()         { *m = MsgUnpauseCrossChains{} }
func (m *MsgUnpauseCrossChains) String() string { return proto.CompactTextString(m) }
func (*MsgUnpauseCrossChains) ProtoMessage()    {}
func (*MsgUnpauseCrossChains) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d12dabcf7836b4c, []int{6}
}
func (m *MsgUnpauseCrossChains) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnpauseCrossChains) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnpauseCrossChains.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnpauseCrossChains) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnpauseCrossChains.Merge(m, src)
}
func (m *MsgUnpauseCrossChains) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnpauseCrossChains) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnpauseCrossChains.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnpauseCrossChains proto.InternalMessageInfo

// MsgUnpauseCrossChainsResponse is the response type
// from a MsgUnpauseCrossChain request.
type MsgUnpauseCrossChainsResponse struct {
}

func (m *MsgUnpauseCrossChainsResponse) Reset()         { *m = MsgUnpauseCrossChainsResponse{} }
func (m *MsgUnpauseCrossChainsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUnpauseCrossChainsResponse) ProtoMessage()    {}
func (*MsgUnpauseCrossChainsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d12dabcf7836b4c, []int{7}
}
func (m *MsgUnpauseCrossChainsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnpauseCrossChainsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnpauseCrossChainsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnpauseCrossChainsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnpauseCrossChainsResponse.Merge(m, src)
}
func (m *MsgUnpauseCrossChainsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnpauseCrossChainsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnpauseCrossChainsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnpauseCrossChainsResponse proto.InternalMessageInfo

// MsgReplaceDepositForBurnResponse allows the orbiter authority
// to replace a sent deposit for burn message.
type MsgReplaceDepositForBurn struct {
	Signer               string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	OriginalMessage      []byte `protobuf:"bytes,2,opt,name=original_message,json=originalMessage,proto3" json:"original_message,omitempty"`
	OriginalAttestation  []byte `protobuf:"bytes,3,opt,name=original_attestation,json=originalAttestation,proto3" json:"original_attestation,omitempty"`
	NewDestinationCaller []byte `protobuf:"bytes,4,opt,name=new_destination_caller,json=newDestinationCaller,proto3" json:"new_destination_caller,omitempty"`
	NewMintRecipient     []byte `protobuf:"bytes,5,opt,name=new_mint_recipient,json=newMintRecipient,proto3" json:"new_mint_recipient,omitempty"`
}

func (m *MsgReplaceDepositForBurn) Reset()         { *m = MsgReplaceDepositForBurn{} }
func (m *MsgReplaceDepositForBurn) String() string { return proto.CompactTextString(m) }
func (*MsgReplaceDepositForBurn) ProtoMessage()    {}
func (*MsgReplaceDepositForBurn) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d12dabcf7836b4c, []int{8}
}
func (m *MsgReplaceDepositForBurn) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgReplaceDepositForBurn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgReplaceDepositForBurn.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgReplaceDepositForBurn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReplaceDepositForBurn.Merge(m, src)
}
func (m *MsgReplaceDepositForBurn) XXX_Size() int {
	return m.Size()
}
func (m *MsgReplaceDepositForBurn) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReplaceDepositForBurn.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReplaceDepositForBurn proto.InternalMessageInfo

// MsgReplaceDepositForBurnResponse is the response type from
// a MsgReplaceDepositForBurn request.
type MsgReplaceDepositForBurnResponse struct {
}

func (m *MsgReplaceDepositForBurnResponse) Reset()         { *m = MsgReplaceDepositForBurnResponse{} }
func (m *MsgReplaceDepositForBurnResponse) String() string { return proto.CompactTextString(m) }
func (*MsgReplaceDepositForBurnResponse) ProtoMessage()    {}
func (*MsgReplaceDepositForBurnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d12dabcf7836b4c, []int{9}
}
func (m *MsgReplaceDepositForBurnResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgReplaceDepositForBurnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgReplaceDepositForBurnResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgReplaceDepositForBurnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReplaceDepositForBurnResponse.Merge(m, src)
}
func (m *MsgReplaceDepositForBurnResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgReplaceDepositForBurnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReplaceDepositForBurnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReplaceDepositForBurnResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgPauseProtocol)(nil), "noble.orbiter.component.forwarder.v1.MsgPauseProtocol")
	proto.RegisterType((*MsgPauseProtocolResponse)(nil), "noble.orbiter.component.forwarder.v1.MsgPauseProtocolResponse")
	proto.RegisterType((*MsgPauseCrossChains)(nil), "noble.orbiter.component.forwarder.v1.MsgPauseCrossChains")
	proto.RegisterType((*MsgPauseCrossChainsResponse)(nil), "noble.orbiter.component.forwarder.v1.MsgPauseCrossChainsResponse")
	proto.RegisterType((*MsgUnpauseProtocol)(nil), "noble.orbiter.component.forwarder.v1.MsgUnpauseProtocol")
	proto.RegisterType((*MsgUnpauseProtocolResponse)(nil), "noble.orbiter.component.forwarder.v1.MsgUnpauseProtocolResponse")
	proto.RegisterType((*MsgUnpauseCrossChains)(nil), "noble.orbiter.component.forwarder.v1.MsgUnpauseCrossChains")
	proto.RegisterType((*MsgUnpauseCrossChainsResponse)(nil), "noble.orbiter.component.forwarder.v1.MsgUnpauseCrossChainsResponse")
	proto.RegisterType((*MsgReplaceDepositForBurn)(nil), "noble.orbiter.component.forwarder.v1.MsgReplaceDepositForBurn")
	proto.RegisterType((*MsgReplaceDepositForBurnResponse)(nil), "noble.orbiter.component.forwarder.v1.MsgReplaceDepositForBurnResponse")
}

func init() {
	proto.RegisterFile("noble/orbiter/component/forwarder/v1/tx.proto", fileDescriptor_6d12dabcf7836b4c)
}

var fileDescriptor_6d12dabcf7836b4c = []byte{
	// 730 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xb1, 0x6f, 0xd3, 0x4c,
	0x1c, 0xcd, 0x35, 0x5f, 0x2b, 0xf5, 0xbe, 0xef, 0xa3, 0xc1, 0x4d, 0xc1, 0x18, 0x9a, 0xa4, 0x56,
	0x11, 0x6d, 0x45, 0x6d, 0x52, 0x10, 0xd0, 0x80, 0x28, 0x4d, 0xaa, 0x4a, 0x1d, 0x22, 0x55, 0x41,
	0x2c, 0x2c, 0x91, 0x6b, 0x1f, 0xe6, 0xa4, 0xf8, 0xce, 0xba, 0xbb, 0x26, 0x74, 0x43, 0x2c, 0x20,
	0x24, 0xa4, 0x4e, 0xac, 0xf4, 0x4f, 0xe8, 0xc0, 0x3f, 0xc0, 0x80, 0xc4, 0x46, 0xc5, 0xc4, 0x88,
	0xda, 0xa1, 0xcc, 0x08, 0x31, 0xa3, 0x38, 0xb6, 0x93, 0x3a, 0xb6, 0xd4, 0xa6, 0x03, 0xb0, 0x44,
	0xf1, 0xef, 0xfd, 0xde, 0xdd, 0x7b, 0xef, 0x72, 0xbf, 0x18, 0xce, 0x13, 0xba, 0xd1, 0x40, 0x3a,
	0x65, 0x1b, 0x58, 0x20, 0xa6, 0x9b, 0xd4, 0x71, 0x29, 0x41, 0x44, 0xe8, 0x8f, 0x29, 0x6b, 0x19,
	0xcc, 0x42, 0x4c, 0x6f, 0x16, 0x75, 0xf1, 0x54, 0x73, 0x19, 0x15, 0x54, 0x9a, 0xf6, 0xda, 0x35,
	0xbf, 0x5d, 0x0b, 0xdb, 0xb5, 0xb0, 0x5d, 0x6b, 0x16, 0x95, 0xb3, 0x86, 0x83, 0x09, 0xd5, 0xbd,
	0xcf, 0x0e, 0x51, 0x39, 0x6f, 0x52, 0xee, 0x50, 0xae, 0x3b, 0xdc, 0x6e, 0x2f, 0xe8, 0x70, 0xdb,
	0x07, 0x2e, 0x74, 0x80, 0xba, 0xf7, 0xa4, 0x77, 0x1e, 0x7c, 0x28, 0x6b, 0x53, 0x9b, 0x76, 0xea,
	0xed, 0x6f, 0x7e, 0x35, 0x17, 0x55, 0xcc, 0x50, 0x7b, 0x45, 0x6c, 0x75, 0x70, 0xf5, 0x3d, 0x80,
	0x99, 0x2a, 0xb7, 0xd7, 0x8d, 0x4d, 0x8e, 0xd6, 0xdb, 0x15, 0x93, 0x36, 0xa4, 0x6b, 0x70, 0x84,
	0x63, 0x9b, 0x20, 0x26, 0x83, 0x02, 0x98, 0x19, 0x2d, 0xcb, 0x9f, 0xdf, 0xcd, 0x67, 0xfd, 0xcd,
	0x96, 0x2d, 0x8b, 0x21, 0xce, 0x1f, 0x08, 0x86, 0x89, 0x5d, 0xf3, 0xfb, 0xa4, 0x32, 0xfc, 0xd7,
	0xf5, 0xd9, 0x75, 0x6c, 0xc9, 0x43, 0x05, 0x30, 0x73, 0x66, 0x61, 0x4a, 0x8b, 0xfa, 0x67, 0x48,
	0x6b, 0x16, 0xb5, 0x60, 0x9f, 0xb5, 0x95, 0x1a, 0x0c, 0x58, 0x6b, 0x56, 0xe9, 0xd6, 0xcb, 0x9d,
	0x7c, 0xea, 0xdb, 0x4e, 0x3e, 0xf5, 0xfc, 0x70, 0x77, 0xce, 0x5f, 0xf8, 0xd5, 0xe1, 0xee, 0x5c,
	0x3e, 0x10, 0xdf, 0x0d, 0xf9, 0x88, 0x5c, 0x55, 0x81, 0x72, 0xd4, 0x42, 0x0d, 0x71, 0x97, 0x12,
	0x8e, 0xd4, 0xef, 0x00, 0x8e, 0x07, 0x60, 0x85, 0x51, 0xce, 0x2b, 0x4f, 0x0c, 0x4c, 0xf8, 0xef,
	0xb1, 0x28, 0xcd, 0xc2, 0x8c, 0x49, 0x37, 0x89, 0x40, 0xcc, 0x35, 0x98, 0xd8, 0xaa, 0x63, 0x8b,
	0xcb, 0xe9, 0x42, 0x7a, 0x66, 0xb4, 0x36, 0xd6, 0x5b, 0x5f, 0xb3, 0x78, 0xa9, 0x94, 0x90, 0x86,
	0x9a, 0x90, 0x46, 0x8f, 0x39, 0x75, 0x12, 0x5e, 0x8c, 0xf1, 0x1c, 0x66, 0xf2, 0x01, 0x40, 0xa9,
	0xca, 0xed, 0x87, 0xc4, 0xfd, 0x03, 0x4e, 0x7d, 0x31, 0xc1, 0xe7, 0x54, 0xbf, 0xcf, 0x88, 0x60,
	0xf5, 0x12, 0x54, 0xfa, 0x6d, 0x84, 0x2e, 0x7f, 0x02, 0x38, 0xd1, 0x85, 0xff, 0xaa, 0xb3, 0xbf,
	0x9b, 0x90, 0xc9, 0x74, 0x62, 0x26, 0xbd, 0xa7, 0x9f, 0x87, 0x93, 0xb1, 0xbe, 0xc3, 0x64, 0x3e,
	0x0d, 0x79, 0x17, 0xa6, 0x86, 0xdc, 0x86, 0x61, 0xa2, 0x15, 0xe4, 0x52, 0x8e, 0xc5, 0x2a, 0x65,
	0xe5, 0x4d, 0x46, 0x06, 0x08, 0x67, 0x16, 0x66, 0x28, 0xc3, 0x36, 0x26, 0x46, 0xa3, 0xee, 0x20,
	0xce, 0x0d, 0x1b, 0x79, 0x09, 0xfd, 0x57, 0x1b, 0x0b, 0xea, 0xd5, 0x4e, 0x59, 0x2a, 0xc2, 0x6c,
	0xd8, 0x6a, 0x08, 0x81, 0xb8, 0x30, 0x04, 0xa6, 0x44, 0x4e, 0x7b, 0xed, 0xe3, 0x01, 0xb6, 0xdc,
	0x85, 0xa4, 0x1b, 0xf0, 0x1c, 0x41, 0xad, 0xba, 0x85, 0xb8, 0xc0, 0xc4, 0x2b, 0xd5, 0x4d, 0xa3,
	0xd1, 0x40, 0x4c, 0xfe, 0xc7, 0x23, 0x65, 0x09, 0x6a, 0xad, 0x74, 0xc1, 0x8a, 0x87, 0x49, 0x57,
	0xa1, 0xd4, 0x66, 0x39, 0x98, 0x88, 0x3a, 0x43, 0x26, 0x76, 0x31, 0x22, 0x42, 0x1e, 0xf6, 0x18,
	0x19, 0x82, 0x5a, 0x55, 0x4c, 0x44, 0x2d, 0xa8, 0x97, 0x96, 0x12, 0xf2, 0xbe, 0xd2, 0x9f, 0x77,
	0x6c, 0x68, 0xaa, 0x0a, 0x0b, 0x49, 0x81, 0x06, 0xa9, 0x2f, 0xfc, 0x18, 0x86, 0xe9, 0x2a, 0xb7,
	0xa5, 0x17, 0x00, 0xfe, 0x7f, 0x74, 0xdc, 0xde, 0xd4, 0x8e, 0xf3, 0x3f, 0xa1, 0x45, 0x67, 0x9c,
	0x72, 0x6f, 0x30, 0x5e, 0xa0, 0x48, 0x7a, 0x0d, 0xe0, 0x58, 0x74, 0x08, 0xdc, 0x3e, 0xf6, 0x9a,
	0x11, 0xa6, 0x72, 0x7f, 0x50, 0x66, 0xa8, 0x67, 0x1b, 0xc0, 0x4c, 0xdf, 0xa0, 0x5e, 0x3c, 0x99,
	0xc9, 0x1e, 0xaa, 0xb2, 0x3c, 0x30, 0x35, 0x94, 0xf4, 0x06, 0x40, 0x29, 0x66, 0x82, 0xdc, 0x39,
	0xa9, 0xd7, 0x5e, 0x59, 0x95, 0x53, 0x90, 0x43, 0x61, 0x6f, 0x01, 0x9c, 0x88, 0xbf, 0xc0, 0xc7,
	0xff, 0x55, 0xc4, 0xf2, 0x95, 0xd5, 0xd3, 0xf1, 0x03, 0x85, 0xca, 0xf0, 0xb3, 0xc3, 0xdd, 0x39,
	0x50, 0x5e, 0xfa, 0xb8, 0x9f, 0x03, 0x7b, 0xfb, 0x39, 0xf0, 0x75, 0x3f, 0x07, 0xb6, 0x0f, 0x72,
	0xa9, 0xbd, 0x83, 0x5c, 0xea, 0xcb, 0x41, 0x2e, 0xf5, 0xe8, 0x72, 0xb0, 0x83, 0x85, 0x9a, 0xba,
	0xd8, 0x72, 0x11, 0x8f, 0x7b, 0xa1, 0xda, 0x18, 0xf1, 0x66, 0xe8, 0xf5, 0x5f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x85, 0xc7, 0xb9, 0xa2, 0x7c, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// PauseProtocol pauses an entire forwarding protocol.
	PauseProtocol(ctx context.Context, in *MsgPauseProtocol, opts ...grpc.CallOption) (*MsgPauseProtocolResponse, error)
	// UnpauseProtocol resumes an entire forwarding protocol.
	UnpauseProtocol(ctx context.Context, in *MsgUnpauseProtocol, opts ...grpc.CallOption) (*MsgUnpauseProtocolResponse, error)
	// PauseCrossChains pauses specific counterparty for a protocol.
	PauseCrossChains(ctx context.Context, in *MsgPauseCrossChains, opts ...grpc.CallOption) (*MsgPauseCrossChainsResponse, error)
	// UnpauseCrossChains resumes specific counterparty pairs for a protocol.
	UnpauseCrossChains(ctx context.Context, in *MsgUnpauseCrossChains, opts ...grpc.CallOption) (*MsgUnpauseCrossChainsResponse, error)
	ReplaceDepositForBurn(ctx context.Context, in *MsgReplaceDepositForBurn, opts ...grpc.CallOption) (*MsgReplaceDepositForBurnResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) PauseProtocol(ctx context.Context, in *MsgPauseProtocol, opts ...grpc.CallOption) (*MsgPauseProtocolResponse, error) {
	out := new(MsgPauseProtocolResponse)
	err := c.cc.Invoke(ctx, "/noble.orbiter.component.forwarder.v1.Msg/PauseProtocol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnpauseProtocol(ctx context.Context, in *MsgUnpauseProtocol, opts ...grpc.CallOption) (*MsgUnpauseProtocolResponse, error) {
	out := new(MsgUnpauseProtocolResponse)
	err := c.cc.Invoke(ctx, "/noble.orbiter.component.forwarder.v1.Msg/UnpauseProtocol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PauseCrossChains(ctx context.Context, in *MsgPauseCrossChains, opts ...grpc.CallOption) (*MsgPauseCrossChainsResponse, error) {
	out := new(MsgPauseCrossChainsResponse)
	err := c.cc.Invoke(ctx, "/noble.orbiter.component.forwarder.v1.Msg/PauseCrossChains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnpauseCrossChains(ctx context.Context, in *MsgUnpauseCrossChains, opts ...grpc.CallOption) (*MsgUnpauseCrossChainsResponse, error) {
	out := new(MsgUnpauseCrossChainsResponse)
	err := c.cc.Invoke(ctx, "/noble.orbiter.component.forwarder.v1.Msg/UnpauseCrossChains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ReplaceDepositForBurn(ctx context.Context, in *MsgReplaceDepositForBurn, opts ...grpc.CallOption) (*MsgReplaceDepositForBurnResponse, error) {
	out := new(MsgReplaceDepositForBurnResponse)
	err := c.cc.Invoke(ctx, "/noble.orbiter.component.forwarder.v1.Msg/ReplaceDepositForBurn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// PauseProtocol pauses an entire forwarding protocol.
	PauseProtocol(context.Context, *MsgPauseProtocol) (*MsgPauseProtocolResponse, error)
	// UnpauseProtocol resumes an entire forwarding protocol.
	UnpauseProtocol(context.Context, *MsgUnpauseProtocol) (*MsgUnpauseProtocolResponse, error)
	// PauseCrossChains pauses specific counterparty for a protocol.
	PauseCrossChains(context.Context, *MsgPauseCrossChains) (*MsgPauseCrossChainsResponse, error)
	// UnpauseCrossChains resumes specific counterparty pairs for a protocol.
	UnpauseCrossChains(context.Context, *MsgUnpauseCrossChains) (*MsgUnpauseCrossChainsResponse, error)
	ReplaceDepositForBurn(context.Context, *MsgReplaceDepositForBurn) (*MsgReplaceDepositForBurnResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) PauseProtocol(ctx context.Context, req *MsgPauseProtocol) (*MsgPauseProtocolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseProtocol not implemented")
}
func (*UnimplementedMsgServer) UnpauseProtocol(ctx context.Context, req *MsgUnpauseProtocol) (*MsgUnpauseProtocolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnpauseProtocol not implemented")
}
func (*UnimplementedMsgServer) PauseCrossChains(ctx context.Context, req *MsgPauseCrossChains) (*MsgPauseCrossChainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseCrossChains not implemented")
}
func (*UnimplementedMsgServer) UnpauseCrossChains(ctx context.Context, req *MsgUnpauseCrossChains) (*MsgUnpauseCrossChainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnpauseCrossChains not implemented")
}
func (*UnimplementedMsgServer) ReplaceDepositForBurn(ctx context.Context, req *MsgReplaceDepositForBurn) (*MsgReplaceDepositForBurnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceDepositForBurn not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_PauseProtocol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPauseProtocol)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PauseProtocol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noble.orbiter.component.forwarder.v1.Msg/PauseProtocol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PauseProtocol(ctx, req.(*MsgPauseProtocol))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnpauseProtocol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnpauseProtocol)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnpauseProtocol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noble.orbiter.component.forwarder.v1.Msg/UnpauseProtocol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnpauseProtocol(ctx, req.(*MsgUnpauseProtocol))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PauseCrossChains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPauseCrossChains)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PauseCrossChains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noble.orbiter.component.forwarder.v1.Msg/PauseCrossChains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PauseCrossChains(ctx, req.(*MsgPauseCrossChains))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnpauseCrossChains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnpauseCrossChains)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnpauseCrossChains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noble.orbiter.component.forwarder.v1.Msg/UnpauseCrossChains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnpauseCrossChains(ctx, req.(*MsgUnpauseCrossChains))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ReplaceDepositForBurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgReplaceDepositForBurn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ReplaceDepositForBurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noble.orbiter.component.forwarder.v1.Msg/ReplaceDepositForBurn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ReplaceDepositForBurn(ctx, req.(*MsgReplaceDepositForBurn))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "noble.orbiter.component.forwarder.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PauseProtocol",
			Handler:    _Msg_PauseProtocol_Handler,
		},
		{
			MethodName: "UnpauseProtocol",
			Handler:    _Msg_UnpauseProtocol_Handler,
		},
		{
			MethodName: "PauseCrossChains",
			Handler:    _Msg_PauseCrossChains_Handler,
		},
		{
			MethodName: "UnpauseCrossChains",
			Handler:    _Msg_UnpauseCrossChains_Handler,
		},
		{
			MethodName: "ReplaceDepositForBurn",
			Handler:    _Msg_ReplaceDepositForBurn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "noble/orbiter/component/forwarder/v1/tx.proto",
}

func (m *MsgPauseProtocol) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPauseProtocol) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPauseProtocol) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProtocolId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProtocolId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPauseProtocolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPauseProtocolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPauseProtocolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgPauseCrossChains) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPauseCrossChains) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPauseCrossChains) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CounterpartyIds) > 0 {
		for iNdEx := len(m.CounterpartyIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CounterpartyIds[iNdEx])
			copy(dAtA[i:], m.CounterpartyIds[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.CounterpartyIds[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.ProtocolId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProtocolId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPauseCrossChainsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPauseCrossChainsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPauseCrossChainsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUnpauseProtocol) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnpauseProtocol) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnpauseProtocol) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProtocolId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProtocolId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUnpauseProtocolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnpauseProtocolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnpauseProtocolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUnpauseCrossChains) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnpauseCrossChains) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnpauseCrossChains) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CounterpartyIds) > 0 {
		for iNdEx := len(m.CounterpartyIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CounterpartyIds[iNdEx])
			copy(dAtA[i:], m.CounterpartyIds[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.CounterpartyIds[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.ProtocolId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProtocolId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUnpauseCrossChainsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnpauseCrossChainsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnpauseCrossChainsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgReplaceDepositForBurn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgReplaceDepositForBurn) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgReplaceDepositForBurn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewMintRecipient) > 0 {
		i -= len(m.NewMintRecipient)
		copy(dAtA[i:], m.NewMintRecipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewMintRecipient)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.NewDestinationCaller) > 0 {
		i -= len(m.NewDestinationCaller)
		copy(dAtA[i:], m.NewDestinationCaller)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewDestinationCaller)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.OriginalAttestation) > 0 {
		i -= len(m.OriginalAttestation)
		copy(dAtA[i:], m.OriginalAttestation)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OriginalAttestation)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OriginalMessage) > 0 {
		i -= len(m.OriginalMessage)
		copy(dAtA[i:], m.OriginalMessage)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OriginalMessage)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgReplaceDepositForBurnResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgReplaceDepositForBurnResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgReplaceDepositForBurnResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgPauseProtocol) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ProtocolId != 0 {
		n += 1 + sovTx(uint64(m.ProtocolId))
	}
	return n
}

func (m *MsgPauseProtocolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgPauseCrossChains) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ProtocolId != 0 {
		n += 1 + sovTx(uint64(m.ProtocolId))
	}
	if len(m.CounterpartyIds) > 0 {
		for _, s := range m.CounterpartyIds {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgPauseCrossChainsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUnpauseProtocol) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ProtocolId != 0 {
		n += 1 + sovTx(uint64(m.ProtocolId))
	}
	return n
}

func (m *MsgUnpauseProtocolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUnpauseCrossChains) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ProtocolId != 0 {
		n += 1 + sovTx(uint64(m.ProtocolId))
	}
	if len(m.CounterpartyIds) > 0 {
		for _, s := range m.CounterpartyIds {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgUnpauseCrossChainsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgReplaceDepositForBurn) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OriginalMessage)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OriginalAttestation)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewDestinationCaller)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewMintRecipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgReplaceDepositForBurnResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgPauseProtocol) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPauseProtocol: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPauseProtocol: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolId", wireType)
			}
			m.ProtocolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProtocolId |= core.ProtocolID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPauseProtocolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPauseProtocolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPauseProtocolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPauseCrossChains) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPauseCrossChains: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPauseCrossChains: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolId", wireType)
			}
			m.ProtocolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProtocolId |= core.ProtocolID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CounterpartyIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CounterpartyIds = append(m.CounterpartyIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPauseCrossChainsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPauseCrossChainsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPauseCrossChainsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnpauseProtocol) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnpauseProtocol: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnpauseProtocol: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolId", wireType)
			}
			m.ProtocolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProtocolId |= core.ProtocolID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnpauseProtocolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnpauseProtocolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnpauseProtocolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnpauseCrossChains) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnpauseCrossChains: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnpauseCrossChains: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolId", wireType)
			}
			m.ProtocolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProtocolId |= core.ProtocolID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CounterpartyIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CounterpartyIds = append(m.CounterpartyIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnpauseCrossChainsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnpauseCrossChainsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnpauseCrossChainsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgReplaceDepositForBurn) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgReplaceDepositForBurn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgReplaceDepositForBurn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginalMessage", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginalMessage = append(m.OriginalMessage[:0], dAtA[iNdEx:postIndex]...)
			if m.OriginalMessage == nil {
				m.OriginalMessage = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginalAttestation", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginalAttestation = append(m.OriginalAttestation[:0], dAtA[iNdEx:postIndex]...)
			if m.OriginalAttestation == nil {
				m.OriginalAttestation = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewDestinationCaller", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewDestinationCaller = append(m.NewDestinationCaller[:0], dAtA[iNdEx:postIndex]...)
			if m.NewDestinationCaller == nil {
				m.NewDestinationCaller = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewMintRecipient", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewMintRecipient = append(m.NewMintRecipient[:0], dAtA[iNdEx:postIndex]...)
			if m.NewMintRecipient == nil {
				m.NewMintRecipient = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgReplaceDepositForBurnResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgReplaceDepositForBurnResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgReplaceDepositForBurnResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
