// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package forwarderv1

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	v1 "github.com/noble-assets/orbiter/v2/api/core/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_EventProtocolPaused             protoreflect.MessageDescriptor
	fd_EventProtocolPaused_protocol_id protoreflect.FieldDescriptor
)

func init() {
	file_noble_orbiter_component_forwarder_v1_events_proto_init()
	md_EventProtocolPaused = File_noble_orbiter_component_forwarder_v1_events_proto.Messages().ByName("EventProtocolPaused")
	fd_EventProtocolPaused_protocol_id = md_EventProtocolPaused.Fields().ByName("protocol_id")
}

var _ protoreflect.Message = (*fastReflection_EventProtocolPaused)(nil)

type fastReflection_EventProtocolPaused EventProtocolPaused

func (x *EventProtocolPaused) ProtoReflect() protoreflect.Message {
	return (*fastReflection_EventProtocolPaused)(x)
}

func (x *EventProtocolPaused) slowProtoReflect() protoreflect.Message {
	mi := &file_noble_orbiter_component_forwarder_v1_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_EventProtocolPaused_messageType fastReflection_EventProtocolPaused_messageType
var _ protoreflect.MessageType = fastReflection_EventProtocolPaused_messageType{}

type fastReflection_EventProtocolPaused_messageType struct{}

func (x fastReflection_EventProtocolPaused_messageType) Zero() protoreflect.Message {
	return (*fastReflection_EventProtocolPaused)(nil)
}
func (x fastReflection_EventProtocolPaused_messageType) New() protoreflect.Message {
	return new(fastReflection_EventProtocolPaused)
}
func (x fastReflection_EventProtocolPaused_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_EventProtocolPaused
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_EventProtocolPaused) Descriptor() protoreflect.MessageDescriptor {
	return md_EventProtocolPaused
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_EventProtocolPaused) Type() protoreflect.MessageType {
	return _fastReflection_EventProtocolPaused_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_EventProtocolPaused) New() protoreflect.Message {
	return new(fastReflection_EventProtocolPaused)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_EventProtocolPaused) Interface() protoreflect.ProtoMessage {
	return (*EventProtocolPaused)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_EventProtocolPaused) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.ProtocolId != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.ProtocolId))
		if !f(fd_EventProtocolPaused_protocol_id, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_EventProtocolPaused) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventProtocolPaused.protocol_id":
		return x.ProtocolId != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventProtocolPaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventProtocolPaused does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventProtocolPaused) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventProtocolPaused.protocol_id":
		x.ProtocolId = 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventProtocolPaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventProtocolPaused does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_EventProtocolPaused) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventProtocolPaused.protocol_id":
		value := x.ProtocolId
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventProtocolPaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventProtocolPaused does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventProtocolPaused) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventProtocolPaused.protocol_id":
		x.ProtocolId = (v1.ProtocolID)(value.Enum())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventProtocolPaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventProtocolPaused does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventProtocolPaused) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventProtocolPaused.protocol_id":
		panic(fmt.Errorf("field protocol_id of message noble.orbiter.component.forwarder.v1.EventProtocolPaused is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventProtocolPaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventProtocolPaused does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_EventProtocolPaused) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventProtocolPaused.protocol_id":
		return protoreflect.ValueOfEnum(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventProtocolPaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventProtocolPaused does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_EventProtocolPaused) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in noble.orbiter.component.forwarder.v1.EventProtocolPaused", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_EventProtocolPaused) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventProtocolPaused) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_EventProtocolPaused) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_EventProtocolPaused) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*EventProtocolPaused)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.ProtocolId != 0 {
			n += 1 + runtime.Sov(uint64(x.ProtocolId))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*EventProtocolPaused)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.ProtocolId != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.ProtocolId))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*EventProtocolPaused)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EventProtocolPaused: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EventProtocolPaused: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ProtocolId", wireType)
				}
				x.ProtocolId = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.ProtocolId |= v1.ProtocolID(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_EventProtocolUnpaused             protoreflect.MessageDescriptor
	fd_EventProtocolUnpaused_protocol_id protoreflect.FieldDescriptor
)

func init() {
	file_noble_orbiter_component_forwarder_v1_events_proto_init()
	md_EventProtocolUnpaused = File_noble_orbiter_component_forwarder_v1_events_proto.Messages().ByName("EventProtocolUnpaused")
	fd_EventProtocolUnpaused_protocol_id = md_EventProtocolUnpaused.Fields().ByName("protocol_id")
}

var _ protoreflect.Message = (*fastReflection_EventProtocolUnpaused)(nil)

type fastReflection_EventProtocolUnpaused EventProtocolUnpaused

func (x *EventProtocolUnpaused) ProtoReflect() protoreflect.Message {
	return (*fastReflection_EventProtocolUnpaused)(x)
}

func (x *EventProtocolUnpaused) slowProtoReflect() protoreflect.Message {
	mi := &file_noble_orbiter_component_forwarder_v1_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_EventProtocolUnpaused_messageType fastReflection_EventProtocolUnpaused_messageType
var _ protoreflect.MessageType = fastReflection_EventProtocolUnpaused_messageType{}

type fastReflection_EventProtocolUnpaused_messageType struct{}

func (x fastReflection_EventProtocolUnpaused_messageType) Zero() protoreflect.Message {
	return (*fastReflection_EventProtocolUnpaused)(nil)
}
func (x fastReflection_EventProtocolUnpaused_messageType) New() protoreflect.Message {
	return new(fastReflection_EventProtocolUnpaused)
}
func (x fastReflection_EventProtocolUnpaused_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_EventProtocolUnpaused
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_EventProtocolUnpaused) Descriptor() protoreflect.MessageDescriptor {
	return md_EventProtocolUnpaused
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_EventProtocolUnpaused) Type() protoreflect.MessageType {
	return _fastReflection_EventProtocolUnpaused_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_EventProtocolUnpaused) New() protoreflect.Message {
	return new(fastReflection_EventProtocolUnpaused)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_EventProtocolUnpaused) Interface() protoreflect.ProtoMessage {
	return (*EventProtocolUnpaused)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_EventProtocolUnpaused) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.ProtocolId != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.ProtocolId))
		if !f(fd_EventProtocolUnpaused_protocol_id, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_EventProtocolUnpaused) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventProtocolUnpaused.protocol_id":
		return x.ProtocolId != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventProtocolUnpaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventProtocolUnpaused does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventProtocolUnpaused) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventProtocolUnpaused.protocol_id":
		x.ProtocolId = 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventProtocolUnpaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventProtocolUnpaused does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_EventProtocolUnpaused) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventProtocolUnpaused.protocol_id":
		value := x.ProtocolId
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventProtocolUnpaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventProtocolUnpaused does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventProtocolUnpaused) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventProtocolUnpaused.protocol_id":
		x.ProtocolId = (v1.ProtocolID)(value.Enum())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventProtocolUnpaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventProtocolUnpaused does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventProtocolUnpaused) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventProtocolUnpaused.protocol_id":
		panic(fmt.Errorf("field protocol_id of message noble.orbiter.component.forwarder.v1.EventProtocolUnpaused is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventProtocolUnpaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventProtocolUnpaused does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_EventProtocolUnpaused) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventProtocolUnpaused.protocol_id":
		return protoreflect.ValueOfEnum(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventProtocolUnpaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventProtocolUnpaused does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_EventProtocolUnpaused) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in noble.orbiter.component.forwarder.v1.EventProtocolUnpaused", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_EventProtocolUnpaused) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventProtocolUnpaused) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_EventProtocolUnpaused) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_EventProtocolUnpaused) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*EventProtocolUnpaused)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.ProtocolId != 0 {
			n += 1 + runtime.Sov(uint64(x.ProtocolId))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*EventProtocolUnpaused)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.ProtocolId != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.ProtocolId))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*EventProtocolUnpaused)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EventProtocolUnpaused: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EventProtocolUnpaused: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ProtocolId", wireType)
				}
				x.ProtocolId = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.ProtocolId |= v1.ProtocolID(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var _ protoreflect.List = (*_EventCrossChainsPaused_2_list)(nil)

type _EventCrossChainsPaused_2_list struct {
	list *[]string
}

func (x *_EventCrossChainsPaused_2_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_EventCrossChainsPaused_2_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_EventCrossChainsPaused_2_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_EventCrossChainsPaused_2_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_EventCrossChainsPaused_2_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message EventCrossChainsPaused at list field CounterpartyIds as it is not of Message kind"))
}

func (x *_EventCrossChainsPaused_2_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_EventCrossChainsPaused_2_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_EventCrossChainsPaused_2_list) IsValid() bool {
	return x.list != nil
}

var (
	md_EventCrossChainsPaused                  protoreflect.MessageDescriptor
	fd_EventCrossChainsPaused_protocol_id      protoreflect.FieldDescriptor
	fd_EventCrossChainsPaused_counterparty_ids protoreflect.FieldDescriptor
)

func init() {
	file_noble_orbiter_component_forwarder_v1_events_proto_init()
	md_EventCrossChainsPaused = File_noble_orbiter_component_forwarder_v1_events_proto.Messages().ByName("EventCrossChainsPaused")
	fd_EventCrossChainsPaused_protocol_id = md_EventCrossChainsPaused.Fields().ByName("protocol_id")
	fd_EventCrossChainsPaused_counterparty_ids = md_EventCrossChainsPaused.Fields().ByName("counterparty_ids")
}

var _ protoreflect.Message = (*fastReflection_EventCrossChainsPaused)(nil)

type fastReflection_EventCrossChainsPaused EventCrossChainsPaused

func (x *EventCrossChainsPaused) ProtoReflect() protoreflect.Message {
	return (*fastReflection_EventCrossChainsPaused)(x)
}

func (x *EventCrossChainsPaused) slowProtoReflect() protoreflect.Message {
	mi := &file_noble_orbiter_component_forwarder_v1_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_EventCrossChainsPaused_messageType fastReflection_EventCrossChainsPaused_messageType
var _ protoreflect.MessageType = fastReflection_EventCrossChainsPaused_messageType{}

type fastReflection_EventCrossChainsPaused_messageType struct{}

func (x fastReflection_EventCrossChainsPaused_messageType) Zero() protoreflect.Message {
	return (*fastReflection_EventCrossChainsPaused)(nil)
}
func (x fastReflection_EventCrossChainsPaused_messageType) New() protoreflect.Message {
	return new(fastReflection_EventCrossChainsPaused)
}
func (x fastReflection_EventCrossChainsPaused_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_EventCrossChainsPaused
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_EventCrossChainsPaused) Descriptor() protoreflect.MessageDescriptor {
	return md_EventCrossChainsPaused
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_EventCrossChainsPaused) Type() protoreflect.MessageType {
	return _fastReflection_EventCrossChainsPaused_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_EventCrossChainsPaused) New() protoreflect.Message {
	return new(fastReflection_EventCrossChainsPaused)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_EventCrossChainsPaused) Interface() protoreflect.ProtoMessage {
	return (*EventCrossChainsPaused)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_EventCrossChainsPaused) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.ProtocolId != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.ProtocolId))
		if !f(fd_EventCrossChainsPaused_protocol_id, value) {
			return
		}
	}
	if len(x.CounterpartyIds) != 0 {
		value := protoreflect.ValueOfList(&_EventCrossChainsPaused_2_list{list: &x.CounterpartyIds})
		if !f(fd_EventCrossChainsPaused_counterparty_ids, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_EventCrossChainsPaused) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsPaused.protocol_id":
		return x.ProtocolId != 0
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsPaused.counterparty_ids":
		return len(x.CounterpartyIds) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventCrossChainsPaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventCrossChainsPaused does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventCrossChainsPaused) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsPaused.protocol_id":
		x.ProtocolId = 0
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsPaused.counterparty_ids":
		x.CounterpartyIds = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventCrossChainsPaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventCrossChainsPaused does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_EventCrossChainsPaused) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsPaused.protocol_id":
		value := x.ProtocolId
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsPaused.counterparty_ids":
		if len(x.CounterpartyIds) == 0 {
			return protoreflect.ValueOfList(&_EventCrossChainsPaused_2_list{})
		}
		listValue := &_EventCrossChainsPaused_2_list{list: &x.CounterpartyIds}
		return protoreflect.ValueOfList(listValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventCrossChainsPaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventCrossChainsPaused does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventCrossChainsPaused) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsPaused.protocol_id":
		x.ProtocolId = (v1.ProtocolID)(value.Enum())
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsPaused.counterparty_ids":
		lv := value.List()
		clv := lv.(*_EventCrossChainsPaused_2_list)
		x.CounterpartyIds = *clv.list
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventCrossChainsPaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventCrossChainsPaused does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventCrossChainsPaused) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsPaused.counterparty_ids":
		if x.CounterpartyIds == nil {
			x.CounterpartyIds = []string{}
		}
		value := &_EventCrossChainsPaused_2_list{list: &x.CounterpartyIds}
		return protoreflect.ValueOfList(value)
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsPaused.protocol_id":
		panic(fmt.Errorf("field protocol_id of message noble.orbiter.component.forwarder.v1.EventCrossChainsPaused is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventCrossChainsPaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventCrossChainsPaused does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_EventCrossChainsPaused) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsPaused.protocol_id":
		return protoreflect.ValueOfEnum(0)
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsPaused.counterparty_ids":
		list := []string{}
		return protoreflect.ValueOfList(&_EventCrossChainsPaused_2_list{list: &list})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventCrossChainsPaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventCrossChainsPaused does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_EventCrossChainsPaused) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in noble.orbiter.component.forwarder.v1.EventCrossChainsPaused", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_EventCrossChainsPaused) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventCrossChainsPaused) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_EventCrossChainsPaused) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_EventCrossChainsPaused) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*EventCrossChainsPaused)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.ProtocolId != 0 {
			n += 1 + runtime.Sov(uint64(x.ProtocolId))
		}
		if len(x.CounterpartyIds) > 0 {
			for _, s := range x.CounterpartyIds {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*EventCrossChainsPaused)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.CounterpartyIds) > 0 {
			for iNdEx := len(x.CounterpartyIds) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.CounterpartyIds[iNdEx])
				copy(dAtA[i:], x.CounterpartyIds[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.CounterpartyIds[iNdEx])))
				i--
				dAtA[i] = 0x12
			}
		}
		if x.ProtocolId != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.ProtocolId))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*EventCrossChainsPaused)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EventCrossChainsPaused: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EventCrossChainsPaused: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ProtocolId", wireType)
				}
				x.ProtocolId = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.ProtocolId |= v1.ProtocolID(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CounterpartyIds", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.CounterpartyIds = append(x.CounterpartyIds, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var _ protoreflect.List = (*_EventCrossChainsUnpaused_2_list)(nil)

type _EventCrossChainsUnpaused_2_list struct {
	list *[]string
}

func (x *_EventCrossChainsUnpaused_2_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_EventCrossChainsUnpaused_2_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_EventCrossChainsUnpaused_2_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_EventCrossChainsUnpaused_2_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_EventCrossChainsUnpaused_2_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message EventCrossChainsUnpaused at list field CounterpartyIds as it is not of Message kind"))
}

func (x *_EventCrossChainsUnpaused_2_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_EventCrossChainsUnpaused_2_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_EventCrossChainsUnpaused_2_list) IsValid() bool {
	return x.list != nil
}

var (
	md_EventCrossChainsUnpaused                  protoreflect.MessageDescriptor
	fd_EventCrossChainsUnpaused_protocol_id      protoreflect.FieldDescriptor
	fd_EventCrossChainsUnpaused_counterparty_ids protoreflect.FieldDescriptor
)

func init() {
	file_noble_orbiter_component_forwarder_v1_events_proto_init()
	md_EventCrossChainsUnpaused = File_noble_orbiter_component_forwarder_v1_events_proto.Messages().ByName("EventCrossChainsUnpaused")
	fd_EventCrossChainsUnpaused_protocol_id = md_EventCrossChainsUnpaused.Fields().ByName("protocol_id")
	fd_EventCrossChainsUnpaused_counterparty_ids = md_EventCrossChainsUnpaused.Fields().ByName("counterparty_ids")
}

var _ protoreflect.Message = (*fastReflection_EventCrossChainsUnpaused)(nil)

type fastReflection_EventCrossChainsUnpaused EventCrossChainsUnpaused

func (x *EventCrossChainsUnpaused) ProtoReflect() protoreflect.Message {
	return (*fastReflection_EventCrossChainsUnpaused)(x)
}

func (x *EventCrossChainsUnpaused) slowProtoReflect() protoreflect.Message {
	mi := &file_noble_orbiter_component_forwarder_v1_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_EventCrossChainsUnpaused_messageType fastReflection_EventCrossChainsUnpaused_messageType
var _ protoreflect.MessageType = fastReflection_EventCrossChainsUnpaused_messageType{}

type fastReflection_EventCrossChainsUnpaused_messageType struct{}

func (x fastReflection_EventCrossChainsUnpaused_messageType) Zero() protoreflect.Message {
	return (*fastReflection_EventCrossChainsUnpaused)(nil)
}
func (x fastReflection_EventCrossChainsUnpaused_messageType) New() protoreflect.Message {
	return new(fastReflection_EventCrossChainsUnpaused)
}
func (x fastReflection_EventCrossChainsUnpaused_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_EventCrossChainsUnpaused
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_EventCrossChainsUnpaused) Descriptor() protoreflect.MessageDescriptor {
	return md_EventCrossChainsUnpaused
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_EventCrossChainsUnpaused) Type() protoreflect.MessageType {
	return _fastReflection_EventCrossChainsUnpaused_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_EventCrossChainsUnpaused) New() protoreflect.Message {
	return new(fastReflection_EventCrossChainsUnpaused)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_EventCrossChainsUnpaused) Interface() protoreflect.ProtoMessage {
	return (*EventCrossChainsUnpaused)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_EventCrossChainsUnpaused) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.ProtocolId != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.ProtocolId))
		if !f(fd_EventCrossChainsUnpaused_protocol_id, value) {
			return
		}
	}
	if len(x.CounterpartyIds) != 0 {
		value := protoreflect.ValueOfList(&_EventCrossChainsUnpaused_2_list{list: &x.CounterpartyIds})
		if !f(fd_EventCrossChainsUnpaused_counterparty_ids, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_EventCrossChainsUnpaused) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused.protocol_id":
		return x.ProtocolId != 0
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused.counterparty_ids":
		return len(x.CounterpartyIds) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventCrossChainsUnpaused) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused.protocol_id":
		x.ProtocolId = 0
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused.counterparty_ids":
		x.CounterpartyIds = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_EventCrossChainsUnpaused) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused.protocol_id":
		value := x.ProtocolId
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused.counterparty_ids":
		if len(x.CounterpartyIds) == 0 {
			return protoreflect.ValueOfList(&_EventCrossChainsUnpaused_2_list{})
		}
		listValue := &_EventCrossChainsUnpaused_2_list{list: &x.CounterpartyIds}
		return protoreflect.ValueOfList(listValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventCrossChainsUnpaused) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused.protocol_id":
		x.ProtocolId = (v1.ProtocolID)(value.Enum())
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused.counterparty_ids":
		lv := value.List()
		clv := lv.(*_EventCrossChainsUnpaused_2_list)
		x.CounterpartyIds = *clv.list
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventCrossChainsUnpaused) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused.counterparty_ids":
		if x.CounterpartyIds == nil {
			x.CounterpartyIds = []string{}
		}
		value := &_EventCrossChainsUnpaused_2_list{list: &x.CounterpartyIds}
		return protoreflect.ValueOfList(value)
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused.protocol_id":
		panic(fmt.Errorf("field protocol_id of message noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_EventCrossChainsUnpaused) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused.protocol_id":
		return protoreflect.ValueOfEnum(0)
	case "noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused.counterparty_ids":
		list := []string{}
		return protoreflect.ValueOfList(&_EventCrossChainsUnpaused_2_list{list: &list})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused"))
		}
		panic(fmt.Errorf("message noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_EventCrossChainsUnpaused) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_EventCrossChainsUnpaused) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventCrossChainsUnpaused) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_EventCrossChainsUnpaused) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_EventCrossChainsUnpaused) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*EventCrossChainsUnpaused)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.ProtocolId != 0 {
			n += 1 + runtime.Sov(uint64(x.ProtocolId))
		}
		if len(x.CounterpartyIds) > 0 {
			for _, s := range x.CounterpartyIds {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*EventCrossChainsUnpaused)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.CounterpartyIds) > 0 {
			for iNdEx := len(x.CounterpartyIds) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.CounterpartyIds[iNdEx])
				copy(dAtA[i:], x.CounterpartyIds[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.CounterpartyIds[iNdEx])))
				i--
				dAtA[i] = 0x12
			}
		}
		if x.ProtocolId != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.ProtocolId))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*EventCrossChainsUnpaused)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EventCrossChainsUnpaused: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EventCrossChainsUnpaused: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ProtocolId", wireType)
				}
				x.ProtocolId = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.ProtocolId |= v1.ProtocolID(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CounterpartyIds", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.CounterpartyIds = append(x.CounterpartyIds, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: noble/orbiter/component/forwarder/v1/events.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventProtocolPaused struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtocolId v1.ProtocolID `protobuf:"varint,1,opt,name=protocol_id,json=protocolId,proto3,enum=noble.orbiter.core.v1.ProtocolID" json:"protocol_id,omitempty"`
}

func (x *EventProtocolPaused) Reset() {
	*x = EventProtocolPaused{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noble_orbiter_component_forwarder_v1_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventProtocolPaused) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventProtocolPaused) ProtoMessage() {}

// Deprecated: Use EventProtocolPaused.ProtoReflect.Descriptor instead.
func (*EventProtocolPaused) Descriptor() ([]byte, []int) {
	return file_noble_orbiter_component_forwarder_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventProtocolPaused) GetProtocolId() v1.ProtocolID {
	if x != nil {
		return x.ProtocolId
	}
	return v1.ProtocolID(0)
}

type EventProtocolUnpaused struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtocolId v1.ProtocolID `protobuf:"varint,1,opt,name=protocol_id,json=protocolId,proto3,enum=noble.orbiter.core.v1.ProtocolID" json:"protocol_id,omitempty"`
}

func (x *EventProtocolUnpaused) Reset() {
	*x = EventProtocolUnpaused{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noble_orbiter_component_forwarder_v1_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventProtocolUnpaused) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventProtocolUnpaused) ProtoMessage() {}

// Deprecated: Use EventProtocolUnpaused.ProtoReflect.Descriptor instead.
func (*EventProtocolUnpaused) Descriptor() ([]byte, []int) {
	return file_noble_orbiter_component_forwarder_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventProtocolUnpaused) GetProtocolId() v1.ProtocolID {
	if x != nil {
		return x.ProtocolId
	}
	return v1.ProtocolID(0)
}

type EventCrossChainsPaused struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtocolId      v1.ProtocolID `protobuf:"varint,1,opt,name=protocol_id,json=protocolId,proto3,enum=noble.orbiter.core.v1.ProtocolID" json:"protocol_id,omitempty"`
	CounterpartyIds []string      `protobuf:"bytes,2,rep,name=counterparty_ids,json=counterpartyIds,proto3" json:"counterparty_ids,omitempty"`
}

func (x *EventCrossChainsPaused) Reset() {
	*x = EventCrossChainsPaused{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noble_orbiter_component_forwarder_v1_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventCrossChainsPaused) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCrossChainsPaused) ProtoMessage() {}

// Deprecated: Use EventCrossChainsPaused.ProtoReflect.Descriptor instead.
func (*EventCrossChainsPaused) Descriptor() ([]byte, []int) {
	return file_noble_orbiter_component_forwarder_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *EventCrossChainsPaused) GetProtocolId() v1.ProtocolID {
	if x != nil {
		return x.ProtocolId
	}
	return v1.ProtocolID(0)
}

func (x *EventCrossChainsPaused) GetCounterpartyIds() []string {
	if x != nil {
		return x.CounterpartyIds
	}
	return nil
}

type EventCrossChainsUnpaused struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtocolId      v1.ProtocolID `protobuf:"varint,1,opt,name=protocol_id,json=protocolId,proto3,enum=noble.orbiter.core.v1.ProtocolID" json:"protocol_id,omitempty"`
	CounterpartyIds []string      `protobuf:"bytes,2,rep,name=counterparty_ids,json=counterpartyIds,proto3" json:"counterparty_ids,omitempty"`
}

func (x *EventCrossChainsUnpaused) Reset() {
	*x = EventCrossChainsUnpaused{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noble_orbiter_component_forwarder_v1_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventCrossChainsUnpaused) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCrossChainsUnpaused) ProtoMessage() {}

// Deprecated: Use EventCrossChainsUnpaused.ProtoReflect.Descriptor instead.
func (*EventCrossChainsUnpaused) Descriptor() ([]byte, []int) {
	return file_noble_orbiter_component_forwarder_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *EventCrossChainsUnpaused) GetProtocolId() v1.ProtocolID {
	if x != nil {
		return x.ProtocolId
	}
	return v1.ProtocolID(0)
}

func (x *EventCrossChainsUnpaused) GetCounterpartyIds() []string {
	if x != nil {
		return x.CounterpartyIds
	}
	return nil
}

var File_noble_orbiter_component_forwarder_v1_events_proto protoreflect.FileDescriptor

var file_noble_orbiter_component_forwarder_v1_events_proto_rawDesc = []byte{
	0x0a, 0x31, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2f, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x65, 0x72, 0x2f,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x2f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x24, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x6f, 0x72, 0x62, 0x69, 0x74,
	0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x2e, 0x66, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x6e, 0x6f, 0x62, 0x6c, 0x65,
	0x2f, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x13, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x50, 0x61, 0x75, 0x73, 0x65, 0x64,
	0x12, 0x42, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x6f, 0x72,
	0x62, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x44, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x49, 0x64, 0x22, 0x5b, 0x0a, 0x15, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x55, 0x6e, 0x70, 0x61, 0x75, 0x73, 0x65, 0x64, 0x12, 0x42, 0x0a,
	0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x6f, 0x72, 0x62, 0x69, 0x74,
	0x65, 0x72, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x49, 0x44, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49,
	0x64, 0x22, 0x87, 0x01, 0x0a, 0x16, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x6f, 0x73, 0x73,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x50, 0x61, 0x75, 0x73, 0x65, 0x64, 0x12, 0x42, 0x0a, 0x0b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x21, 0x2e, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x65,
	0x72, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x49, 0x44, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x64,
	0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x64, 0x73, 0x22, 0x89, 0x01, 0x0a, 0x18,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x73,
	0x55, 0x6e, 0x70, 0x61, 0x75, 0x73, 0x65, 0x64, 0x12, 0x42, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e,
	0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x44,
	0x52, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x70,
	0x61, 0x72, 0x74, 0x79, 0x49, 0x64, 0x73, 0x42, 0xc5, 0x02, 0x0a, 0x28, 0x63, 0x6f, 0x6d, 0x2e,
	0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x57, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2d, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x6f, 0x72, 0x62,
	0x69, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x62, 0x6c,
	0x65, 0x2f, 0x6f, 0x72, 0x62, 0x69, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x2f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x76, 0x31,
	0x3b, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x72, 0x76, 0x31, 0xa2, 0x02, 0x04, 0x4e,
	0x4f, 0x43, 0x46, 0xaa, 0x02, 0x24, 0x4e, 0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x4f, 0x72, 0x62, 0x69,
	0x74, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x6f,
	0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x24, 0x4e, 0x6f, 0x62,
	0x6c, 0x65, 0x5c, 0x4f, 0x72, 0x62, 0x69, 0x74, 0x65, 0x72, 0x5c, 0x43, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x5c, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x72, 0x5c, 0x56,
	0x31, 0xe2, 0x02, 0x30, 0x4e, 0x6f, 0x62, 0x6c, 0x65, 0x5c, 0x4f, 0x72, 0x62, 0x69, 0x74, 0x65,
	0x72, 0x5c, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5c, 0x46, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x65, 0x72, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x28, 0x4e, 0x6f, 0x62, 0x6c, 0x65, 0x3a, 0x3a, 0x4f, 0x72,
	0x62, 0x69, 0x74, 0x65, 0x72, 0x3a, 0x3a, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x3a, 0x3a, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_noble_orbiter_component_forwarder_v1_events_proto_rawDescOnce sync.Once
	file_noble_orbiter_component_forwarder_v1_events_proto_rawDescData = file_noble_orbiter_component_forwarder_v1_events_proto_rawDesc
)

func file_noble_orbiter_component_forwarder_v1_events_proto_rawDescGZIP() []byte {
	file_noble_orbiter_component_forwarder_v1_events_proto_rawDescOnce.Do(func() {
		file_noble_orbiter_component_forwarder_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_noble_orbiter_component_forwarder_v1_events_proto_rawDescData)
	})
	return file_noble_orbiter_component_forwarder_v1_events_proto_rawDescData
}

var file_noble_orbiter_component_forwarder_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_noble_orbiter_component_forwarder_v1_events_proto_goTypes = []interface{}{
	(*EventProtocolPaused)(nil),      // 0: noble.orbiter.component.forwarder.v1.EventProtocolPaused
	(*EventProtocolUnpaused)(nil),    // 1: noble.orbiter.component.forwarder.v1.EventProtocolUnpaused
	(*EventCrossChainsPaused)(nil),   // 2: noble.orbiter.component.forwarder.v1.EventCrossChainsPaused
	(*EventCrossChainsUnpaused)(nil), // 3: noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused
	(v1.ProtocolID)(0),               // 4: noble.orbiter.core.v1.ProtocolID
}
var file_noble_orbiter_component_forwarder_v1_events_proto_depIdxs = []int32{
	4, // 0: noble.orbiter.component.forwarder.v1.EventProtocolPaused.protocol_id:type_name -> noble.orbiter.core.v1.ProtocolID
	4, // 1: noble.orbiter.component.forwarder.v1.EventProtocolUnpaused.protocol_id:type_name -> noble.orbiter.core.v1.ProtocolID
	4, // 2: noble.orbiter.component.forwarder.v1.EventCrossChainsPaused.protocol_id:type_name -> noble.orbiter.core.v1.ProtocolID
	4, // 3: noble.orbiter.component.forwarder.v1.EventCrossChainsUnpaused.protocol_id:type_name -> noble.orbiter.core.v1.ProtocolID
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_noble_orbiter_component_forwarder_v1_events_proto_init() }
func file_noble_orbiter_component_forwarder_v1_events_proto_init() {
	if File_noble_orbiter_component_forwarder_v1_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_noble_orbiter_component_forwarder_v1_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventProtocolPaused); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noble_orbiter_component_forwarder_v1_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventProtocolUnpaused); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noble_orbiter_component_forwarder_v1_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventCrossChainsPaused); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noble_orbiter_component_forwarder_v1_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventCrossChainsUnpaused); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_noble_orbiter_component_forwarder_v1_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_noble_orbiter_component_forwarder_v1_events_proto_goTypes,
		DependencyIndexes: file_noble_orbiter_component_forwarder_v1_events_proto_depIdxs,
		MessageInfos:      file_noble_orbiter_component_forwarder_v1_events_proto_msgTypes,
	}.Build()
	File_noble_orbiter_component_forwarder_v1_events_proto = out.File
	file_noble_orbiter_component_forwarder_v1_events_proto_rawDesc = nil
	file_noble_orbiter_component_forwarder_v1_events_proto_goTypes = nil
	file_noble_orbiter_component_forwarder_v1_events_proto_depIdxs = nil
}
