// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: noble/orbiter/controller/forwarding/v1/hyperlane.proto

package forwarding

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// HypAttributes defines the concrete implementation of the
// ForwardingAttributes interface to execute a cross-chain routing
// via the Hyperlane protocol.
type HypAttributes struct {
	// token_id represents the unique ID assigned to a token by the Hyperlane
	// app router.
	TokenId []byte `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// destination_domain represents the Hyperlane destination
	// domain identifier: https://docs.hyperlane.xyz/docs/reference/domains.
	DestinationDomain uint32 `protobuf:"varint,2,opt,name=destination_domain,json=destinationDomain,proto3" json:"destination_domain,omitempty"`
	// recipient is the address of the recipient account in the
	// destination domain.
	Recipient []byte `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// custom_hook_id is the optional ID of the custom hook used instead of the
	// default hook of the mailbox. This hook is executed after the mailbox
	// required hook.
	CustomHookId []byte `protobuf:"bytes,4,opt,name=custom_hook_id,json=customHookId,proto3" json:"custom_hook_id,omitempty"`
	// custom_hook_metadata is the HEX encoded metadata passed to the Hyperlane
	// post dispatch hook.
	CustomHookMetadata string `protobuf:"bytes,5,opt,name=custom_hook_metadata,json=customHookMetadata,proto3" json:"custom_hook_metadata,omitempty"`
	// gas_limit is the maximum gas allowed for the execution of the
	// destination transaction.
	GasLimit cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=gas_limit,json=gasLimit,proto3,customtype=cosmossdk.io/math.Int" json:"gas_limit"`
	// max_fee is the maximum fee allowed for the execution of post dispatch hooks.
	MaxFee types.Coin `protobuf:"bytes,7,opt,name=max_fee,json=maxFee,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"max_fee"`
}

func (m *HypAttributes) Reset()         { *m = HypAttributes{} }
func (m *HypAttributes) String() string { return proto.CompactTextString(m) }
func (*HypAttributes) ProtoMessage()    {}
func (*HypAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9712c0c871a3a243, []int{0}
}
func (m *HypAttributes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HypAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HypAttributes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HypAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HypAttributes.Merge(m, src)
}
func (m *HypAttributes) XXX_Size() int {
	return m.Size()
}
func (m *HypAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_HypAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_HypAttributes proto.InternalMessageInfo

func (m *HypAttributes) GetTokenId() []byte {
	if m != nil {
		return m.TokenId
	}
	return nil
}

func (m *HypAttributes) GetDestinationDomain() uint32 {
	if m != nil {
		return m.DestinationDomain
	}
	return 0
}

func (m *HypAttributes) GetRecipient() []byte {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *HypAttributes) GetCustomHookId() []byte {
	if m != nil {
		return m.CustomHookId
	}
	return nil
}

func (m *HypAttributes) GetCustomHookMetadata() string {
	if m != nil {
		return m.CustomHookMetadata
	}
	return ""
}

func (m *HypAttributes) GetMaxFee() types.Coin {
	if m != nil {
		return m.MaxFee
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*HypAttributes)(nil), "noble.orbiter.controller.forwarding.v1.HypAttributes")
}

func init() {
	proto.RegisterFile("noble/orbiter/controller/forwarding/v1/hyperlane.proto", fileDescriptor_9712c0c871a3a243)
}

var fileDescriptor_9712c0c871a3a243 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x41, 0x6b, 0x13, 0x5d,
	0x14, 0xcd, 0x7c, 0xfd, 0x4c, 0x9a, 0x31, 0x15, 0x3a, 0x54, 0x98, 0x14, 0x99, 0x04, 0x51, 0x89,
	0x85, 0xbc, 0xd7, 0x28, 0xb8, 0xd0, 0x95, 0x51, 0x42, 0x03, 0x76, 0x13, 0x70, 0xe3, 0x66, 0x78,
	0x33, 0x73, 0x3b, 0x79, 0x64, 0xe6, 0xdd, 0x30, 0xef, 0x26, 0x36, 0xfe, 0x0a, 0xd7, 0xfe, 0x02,
	0x71, 0xd5, 0x45, 0xff, 0x82, 0x50, 0x5c, 0x15, 0x57, 0xe2, 0xa2, 0x4a, 0xb2, 0xe8, 0xdf, 0x90,
	0x79, 0x33, 0x34, 0x11, 0xdc, 0xcc, 0xbc, 0x7b, 0xcf, 0x39, 0xf7, 0x3e, 0xde, 0x39, 0xf6, 0x33,
	0x85, 0x41, 0x02, 0x1c, 0xb3, 0x40, 0x12, 0x64, 0x3c, 0x44, 0x45, 0x19, 0x26, 0x09, 0x64, 0xfc,
	0x04, 0xb3, 0xf7, 0x22, 0x8b, 0xa4, 0x8a, 0xf9, 0xbc, 0xc7, 0xc7, 0x8b, 0x29, 0x64, 0x89, 0x50,
	0xc0, 0xa6, 0x19, 0x12, 0x3a, 0x8f, 0x8c, 0x8e, 0x95, 0x3a, 0xb6, 0xd6, 0xb1, 0xb5, 0x8e, 0xcd,
	0x7b, 0xfb, 0xbb, 0x22, 0x95, 0x0a, 0xb9, 0xf9, 0x16, 0xd2, 0x7d, 0x2f, 0x44, 0x9d, 0xa2, 0xe6,
	0x81, 0xd0, 0xc0, 0xe7, 0xbd, 0x00, 0x48, 0xf4, 0x78, 0x88, 0x52, 0x95, 0x78, 0xb3, 0xc0, 0x7d,
	0x53, 0xf1, 0xa2, 0x28, 0xa1, 0xbd, 0x18, 0x63, 0x2c, 0xfa, 0xf9, 0xa9, 0xe8, 0xde, 0xff, 0xba,
	0x65, 0xef, 0x1c, 0x2d, 0xa6, 0x2f, 0x89, 0x32, 0x19, 0xcc, 0x08, 0xb4, 0xd3, 0xb4, 0xb7, 0x09,
	0x27, 0xa0, 0x7c, 0x19, 0xb9, 0x56, 0xdb, 0xea, 0x34, 0x46, 0x35, 0x53, 0x0f, 0x23, 0xa7, 0x6b,
	0x3b, 0x11, 0x68, 0x92, 0x4a, 0x90, 0x44, 0xe5, 0x47, 0x98, 0x0a, 0xa9, 0xdc, 0xff, 0xda, 0x56,
	0x67, 0x67, 0xb4, 0xbb, 0x81, 0xbc, 0x36, 0x80, 0x73, 0xcf, 0xae, 0x67, 0x10, 0xca, 0xa9, 0x04,
	0x45, 0xee, 0x96, 0x19, 0xb5, 0x6e, 0x38, 0x0f, 0xec, 0x3b, 0xe1, 0x4c, 0x13, 0xa6, 0xfe, 0x18,
	0x71, 0x92, 0x6f, 0xfb, 0xdf, 0x50, 0x1a, 0x45, 0xf7, 0x08, 0x71, 0x32, 0x8c, 0x9c, 0x43, 0x7b,
	0x6f, 0x93, 0x95, 0x02, 0x89, 0x48, 0x90, 0x70, 0x6f, 0xb5, 0xad, 0x4e, 0x7d, 0xe4, 0xac, 0xb9,
	0xc7, 0x25, 0xe2, 0x1c, 0xdb, 0xf5, 0x58, 0x68, 0x3f, 0x91, 0xa9, 0x24, 0xb7, 0x9a, 0xd3, 0xfa,
	0x87, 0x17, 0x57, 0xad, 0xca, 0xcf, 0xab, 0xd6, 0xdd, 0xe2, 0x41, 0x74, 0x34, 0x61, 0x12, 0x79,
	0x2a, 0x68, 0xcc, 0x86, 0x8a, 0xbe, 0x9f, 0x77, 0xed, 0xf2, 0xa5, 0x86, 0x8a, 0x3e, 0x5f, 0x9f,
	0x1d, 0x58, 0xa3, 0xed, 0x58, 0xe8, 0x37, 0xf9, 0x04, 0xe7, 0x83, 0x5d, 0x4b, 0xc5, 0xa9, 0x7f,
	0x02, 0xe0, 0xd6, 0xda, 0x56, 0xe7, 0xf6, 0x93, 0x26, 0x2b, 0xc9, 0xb9, 0x07, 0xac, 0xf4, 0x80,
	0xbd, 0x42, 0xa9, 0xfa, 0x83, 0x7c, 0xcf, 0x97, 0x5f, 0xad, 0x4e, 0x2c, 0x69, 0x3c, 0x0b, 0x58,
	0x88, 0x69, 0xe9, 0x41, 0xf9, 0xeb, 0xea, 0x68, 0xc2, 0x69, 0x31, 0x05, 0x6d, 0x04, 0xfa, 0xd3,
	0xf5, 0xd9, 0x41, 0x23, 0x81, 0x58, 0x84, 0x0b, 0x3f, 0x77, 0x51, 0x17, 0xdb, 0xab, 0xa9, 0x38,
	0x1d, 0x00, 0x3c, 0x7f, 0xfc, 0xed, 0xbc, 0xfb, 0xf0, 0xef, 0xb0, 0xcc, 0x7b, 0x6c, 0x70, 0x13,
	0x92, 0xb5, 0x6b, 0xfd, 0xb7, 0x17, 0x4b, 0xcf, 0xba, 0x5c, 0x7a, 0xd6, 0xef, 0xa5, 0x67, 0x7d,
	0x5c, 0x79, 0x95, 0xcb, 0x95, 0x57, 0xf9, 0xb1, 0xf2, 0x2a, 0xef, 0x5e, 0x6c, 0x5c, 0xc6, 0xcc,
	0xea, 0x0a, 0xad, 0x81, 0xf4, 0x4d, 0x6e, 0xcd, 0x7d, 0xfe, 0x9d, 0xde, 0xa0, 0x6a, 0x52, 0xf2,
	0xf4, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x65, 0x07, 0x62, 0x09, 0xeb, 0x02, 0x00, 0x00,
}

func (m *HypAttributes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HypAttributes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HypAttributes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MaxFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintHyperlane(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.GasLimit.Size()
		i -= size
		if _, err := m.GasLimit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintHyperlane(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.CustomHookMetadata) > 0 {
		i -= len(m.CustomHookMetadata)
		copy(dAtA[i:], m.CustomHookMetadata)
		i = encodeVarintHyperlane(dAtA, i, uint64(len(m.CustomHookMetadata)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.CustomHookId) > 0 {
		i -= len(m.CustomHookId)
		copy(dAtA[i:], m.CustomHookId)
		i = encodeVarintHyperlane(dAtA, i, uint64(len(m.CustomHookId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintHyperlane(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x1a
	}
	if m.DestinationDomain != 0 {
		i = encodeVarintHyperlane(dAtA, i, uint64(m.DestinationDomain))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TokenId) > 0 {
		i -= len(m.TokenId)
		copy(dAtA[i:], m.TokenId)
		i = encodeVarintHyperlane(dAtA, i, uint64(len(m.TokenId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintHyperlane(dAtA []byte, offset int, v uint64) int {
	offset -= sovHyperlane(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HypAttributes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TokenId)
	if l > 0 {
		n += 1 + l + sovHyperlane(uint64(l))
	}
	if m.DestinationDomain != 0 {
		n += 1 + sovHyperlane(uint64(m.DestinationDomain))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovHyperlane(uint64(l))
	}
	l = len(m.CustomHookId)
	if l > 0 {
		n += 1 + l + sovHyperlane(uint64(l))
	}
	l = len(m.CustomHookMetadata)
	if l > 0 {
		n += 1 + l + sovHyperlane(uint64(l))
	}
	l = m.GasLimit.Size()
	n += 1 + l + sovHyperlane(uint64(l))
	l = m.MaxFee.Size()
	n += 1 + l + sovHyperlane(uint64(l))
	return n
}

func sovHyperlane(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHyperlane(x uint64) (n int) {
	return sovHyperlane(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HypAttributes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHyperlane
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HypAttributes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HypAttributes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHyperlane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHyperlane
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHyperlane
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenId = append(m.TokenId[:0], dAtA[iNdEx:postIndex]...)
			if m.TokenId == nil {
				m.TokenId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationDomain", wireType)
			}
			m.DestinationDomain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHyperlane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DestinationDomain |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHyperlane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHyperlane
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHyperlane
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = append(m.Recipient[:0], dAtA[iNdEx:postIndex]...)
			if m.Recipient == nil {
				m.Recipient = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustomHookId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHyperlane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHyperlane
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHyperlane
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CustomHookId = append(m.CustomHookId[:0], dAtA[iNdEx:postIndex]...)
			if m.CustomHookId == nil {
				m.CustomHookId = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustomHookMetadata", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHyperlane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHyperlane
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHyperlane
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CustomHookMetadata = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasLimit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHyperlane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHyperlane
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHyperlane
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GasLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHyperlane
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHyperlane
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHyperlane
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHyperlane(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHyperlane
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHyperlane(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHyperlane
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHyperlane
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHyperlane
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHyperlane
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHyperlane
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHyperlane
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHyperlane        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHyperlane          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHyperlane = fmt.Errorf("proto: unexpected end of group")
)
