// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: noble/orbiter/component/executor/v1/query.proto

package executorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_PausedActions_FullMethodName  = "/noble.orbiter.component.executor.v1.Query/PausedActions"
	Query_IsActionPaused_FullMethodName = "/noble.orbiter.component.executor.v1.Query/IsActionPaused"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC query service for the Orbiter
// executor component.
type QueryClient interface {
	PausedActions(ctx context.Context, in *QueryPausedActionsRequest, opts ...grpc.CallOption) (*QueryPausedActionsResponse, error)
	IsActionPaused(ctx context.Context, in *QueryIsActionPausedRequest, opts ...grpc.CallOption) (*QueryIsActionPausedResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) PausedActions(ctx context.Context, in *QueryPausedActionsRequest, opts ...grpc.CallOption) (*QueryPausedActionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPausedActionsResponse)
	err := c.cc.Invoke(ctx, Query_PausedActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IsActionPaused(ctx context.Context, in *QueryIsActionPausedRequest, opts ...grpc.CallOption) (*QueryIsActionPausedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryIsActionPausedResponse)
	err := c.cc.Invoke(ctx, Query_IsActionPaused_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC query service for the Orbiter
// executor component.
type QueryServer interface {
	PausedActions(context.Context, *QueryPausedActionsRequest) (*QueryPausedActionsResponse, error)
	IsActionPaused(context.Context, *QueryIsActionPausedRequest) (*QueryIsActionPausedResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) PausedActions(context.Context, *QueryPausedActionsRequest) (*QueryPausedActionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PausedActions not implemented")
}
func (UnimplementedQueryServer) IsActionPaused(context.Context, *QueryIsActionPausedRequest) (*QueryIsActionPausedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsActionPaused not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call pancis, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_PausedActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPausedActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PausedActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PausedActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PausedActions(ctx, req.(*QueryPausedActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IsActionPaused_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIsActionPausedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IsActionPaused(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_IsActionPaused_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IsActionPaused(ctx, req.(*QueryIsActionPausedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "noble.orbiter.component.executor.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PausedActions",
			Handler:    _Query_PausedActions_Handler,
		},
		{
			MethodName: "IsActionPaused",
			Handler:    _Query_IsActionPaused_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "noble/orbiter/component/executor/v1/query.proto",
}
