[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
auto_detect_remappings = false
remappings = ["forge-std=node_modules/forge-std/src", "@hyperlane=node_modules/@hyperlane-xyz/core/contracts", "@openzeppelin=node_modules/@openzeppelin"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options